spring:
  application:
    name: ms-poll
  datasource:
    url: jdbc:h2:file:./challenge;
    username: test
    password: test
    driverClassName: org.h2.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2/console

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}

poll:
  default:
    time: 1

rabbitmq:
  queue:
    result-publisher: result-publisher
