spring:
  application:
    name: ms-user
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2/console

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
